### PR TITLE
Run tests in CI

### PR DESCRIPTION
**Pull request by bjosv**
Initial and simple steps to compile and run tests in CI.

### CODE REVIEW

**Comment by bjosv** [comment]
Current state is that eunit requires a single running redis, and common tests requires `redis-cli`.
Common tests will start a cluster by using containers from within the tests, but use redis-cli to trigger manual failover and many other scenarios.

**Review by zuiderkwast — APPROVED** [review]
Very nice.

So the common-tests depend on docker and might download a Redis image on the fly when running the tests?

**Comment by bjosv** [comment]
> So the common-tests depend on docker and might download a Redis image on the fly when running the tests?

Yes, unless already existing, it downloads all containers layers needed. Currently it does not specify which version, which means latest, which currently is Redis 7.0.1.
I guess we would like to change this to be able to test redis compatibility.

**Comment by zuiderkwast** [comment]
I'm skeptical to downloading stuff as part of running the tests. It's better if it's downloaded in another command such as `rebar3 as test get-deps` (which would work if this would be erlang deps for the tests).

**Pull request merged**
